version: "3"
services:
  nginx:
    image: 'ronhachmon/multi-nginx'
    ports:
      - "80:80"
    mem_limit : 128m
    hostname: nginx
  api:
    image: 'ronhachmon/multi-server'
    hostname: api
    mem_limit : 128m
    restart : on-failure
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: 'ronhachmon/multi-client'
    mem_limit : 128m
    hostname: client
  worker:
    image: 'ronhachmon/multi-worker'
    mem_limit : 128m
    hostname: client
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
