version: "3"
services:
  nginx:
    image: 'rallycoding/multi-nginx'
    ports:
      - "80:80"
    mem_limit : 128m
    hostname: nginx
  api:
    image: 'rallycoding/multi-server'
    hostname: api
    mem_limit : 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: 'rallycoding/multi-client'
    mem_limit : 128m
    hostname: client
  worker:
    image: 'rallycoding/multi-worker'
    mem_limit : 128m
    hostname: client
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
