name: Deploy images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build images
        run: |
          docker build -t ronhachmon/multi-client ./client
          docker build -t ronhachmon/multi-nginx ./nginx
          docker build -t ronhachmon/multi-server ./server
          docker build -t ronhachmon/multi-worker ./worker

      - name: Push images to Hub
        run: |
          docker push ronhachmon/multi-client
          docker push ronhachmon/multi-nginx
          docker push ronhachmon/multi-server
          docker push ronhachmon/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi-container
          environment_name: Docker-multi-container-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-858189250353
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip